const SPECIAL_KEYS: string[] = [
    "Tab",
    "Shift",
    "Shift",
    "Control",
    "Control",
    "Alt",
    "Alt",
    "Pause",
    "CapsLock",
    "Escape",
    "PageUp",
    "PageDown",
    "End",
    "Home",
    "ArrowLeft",
    "ArrowUp",
    "ArrowRight",
    "ArrowDown",
    "PrintScreen",
    "Insert",
    "Meta",
    "Meta",
    "ContextMenu",
    "F1",
    "F2",
    "F3",
    "F4",
    "F5",
    "F6",
    "F7",
    "F8",
    "F9",
    "F10",
    "F11",
    "F12",
    "NumLock",
    "ScrollLock",
    "AudioVolumeMute",
    "AudioVolumeDown",
    "AudioVolumeUp",
    "LaunchMediaPlayer",
    "LaunchApplication1",
    "LaunchApplication2"
];
function isSpecialKey(event: KeyboardEvent): boolean {
    return SPECIAL_KEYS.includes(event.key);
}

export {isSpecialKey};